# Generated by Django 2.1.15 on 2020-04-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danie',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=50)),
            ],
            options={
                'db_table': 'Danie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diety',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=50)),
                ('data_dodania', models.DateField(db_column='Data_dodania')),
                ('wersja', models.CharField(blank=True, db_column='Wersja', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Diety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KategoriaProduktow',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(blank=True, db_column='Nazwa', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Kategoria_produktow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KategorieDan',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=50)),
            ],
            options={
                'db_table': 'Kategorie_dan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacjenci',
            fields=[
                ('id_pacjenta', models.AutoField(db_column='Id_pacjenta', primary_key=True, serialize=False)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=50)),
                ('imie', models.CharField(db_column='Imie', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=50, null=True)),
                ('data_ur', models.DateField(db_column='Data_ur')),
            ],
            options={
                'db_table': 'Pacjenci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduktyZywn',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=50)),
                ('kcal', models.DecimalField(db_column='Kcal', decimal_places=0, max_digits=18)),
            ],
            options={
                'db_table': 'Produkty_zywn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkladnikiZyw',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nazwa', models.CharField(db_column='Nazwa', max_length=50)),
            ],
            options={
                'db_table': 'Skladniki_zyw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypDiety',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('typ', models.CharField(db_column='Typ', max_length=50)),
            ],
            options={
                'db_table': 'Typ_diety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wizyty',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(db_column='Data')),
                ('potwierdzona', models.BooleanField(blank=True, db_column='Potwierdzona', null=True)),
                ('zakonczona', models.BooleanField(blank=True, db_column='Zakonczona', null=True)),
            ],
            options={
                'db_table': 'Wizyty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WynikiBadan',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('data_badania', models.DateField(db_column='Data_badania')),
                ('waga', models.DecimalField(blank=True, db_column='Waga', decimal_places=0, max_digits=18, null=True)),
                ('plytki_krwi', models.DecimalField(blank=True, db_column='Plytki_krwi', decimal_places=0, max_digits=18, null=True)),
                ('bmi', models.DecimalField(blank=True, db_column='BMI', decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Wyniki_badan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DanieProdukt',
            fields=[
                ('id_dania', models.ForeignKey(db_column='Id_dania', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='OnlineDietetyk.Danie')),
                ('prod_na_100g', models.DecimalField(db_column='Prod_na_100g', decimal_places=0, max_digits=18)),
            ],
            options={
                'db_table': 'Danie_produkt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DietaDanie',
            fields=[
                ('id_diety', models.ForeignKey(db_column='Id_diety', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='OnlineDietetyk.Diety')),
            ],
            options={
                'db_table': 'Dieta_danie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacjentDieta',
            fields=[
                ('id_pacjenta', models.ForeignKey(db_column='Id_pacjenta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='OnlineDietetyk.Pacjenci')),
                ('aktywna', models.BooleanField(db_column='Aktywna')),
                ('data_rozpoczecia', models.DateField(blank=True, db_column='Data_rozpoczecia', null=True)),
                ('data_zakonczenia', models.DateField(blank=True, db_column='Data_zakonczenia', null=True)),
            ],
            options={
                'db_table': 'Pacjent_dieta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProduktSkladnik',
            fields=[
                ('id_prod', models.ForeignKey(db_column='Id_prod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='OnlineDietetyk.ProduktyZywn')),
                ('proc_skl', models.IntegerField(db_column='Proc_skl')),
            ],
            options={
                'db_table': 'Produkt_skladnik',
                'managed': False,
            },
        ),
    ]
